# Generated by Django 5.2.1 on 2025-05-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool", models.CharField(max_length=50)),
                ("args", models.JSONField()),
                ("in_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("out_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("status", models.CharField(default="success", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
