"""
Django settings for pdfshell_srv project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os                 # Import os for environment variables
import dj_database_url    # Import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PDF_FILES_ROOT = BASE_DIR / "files"
PDF_UPLOADS_ROOT = BASE_DIR / "uploads"

DEFAULT_SHARED_FILES = [
    "sample1.pdf",
    "sample2.pdf",
    "stamp1.png", # Assuming stamp.png is also a default shared file in files/
    "stamp2.png",
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^wg=$d++skz5u^%myet4v(e3b@t56(fj5bscp#*r)q(-%p2i-5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True' # Read DEBUG from env, default to True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') # Read ALLOWED_HOSTS from env


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'coreapi.apps.CoreapiConfig',
    'apptrace.apps.TraceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdfshell_srv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdfshell_srv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default to SQLite if DATABASE_URL is not set (e.g., for local non-Docker testing)
# SQLITE_DEFAULT_URL = 'sqlite:///' + str(BASE_DIR / 'db.sqlite3')
# DATABASE_URL = os.getenv('DATABASE_URL', SQLITE_DEFAULT_URL) # 暫時註解

# # 根據環境變數決定 DB host，預設為 'db' (用於 Docker 內部)
# # 在本地執行 manage.py 時，可以設定 DB_HOST=localhost
# DB_HOST = os.getenv('DB_HOST', 'db') # 註解掉

DATABASES = {
    # 'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600) # 暫時註解
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pdfshell_db',     # 直接使用 .env 中的值
        'USER': 'pdfshell_user',    # 直接使用 .env 中的值
        'PASSWORD': 'pdfshell_pass', # 直接使用 .env 中的值
        'HOST': 'localhost',       # 直接使用 .env 中的值 (POSTGRES_HOST 的預期值)
        'PORT': '5432',            # 直接使用 .env 中的值
        'OPTIONS': {
            'client_encoding': 'UTF8', # 明確指定客戶端編碼
        },
    }
}

# DEBUGGING: Print effective database connection parameters
db_settings_effective = DATABASES['default']
print(f"DEBUG_SETTINGS PY: HOST: {db_settings_effective['HOST']}")
print(f"DEBUG_SETTINGS PY: NAME: {db_settings_effective['NAME']}")
print(f"DEBUG_SETTINGS PY: USER: {db_settings_effective['USER']}")
print(f"DEBUG_SETTINGS PY: PASSWORD: {db_settings_effective['PASSWORD']}")
print(f"DEBUG_SETTINGS PY: PORT: {db_settings_effective['PORT']}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
